import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "WVSU University Recognition 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-darkblue flex flex-col min-h-screen">
        {children}
        <Navbar/>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
